### ISSUE TITLE
Add company logo to show on the KnowNepal Website

### ISSUE THREAD

**Issue by thenishantsapkota** [Know-Nepal/tech-companies#95]
## Is your feature request related to a problem? Please describe.
Yes, actually the Tech Companies section of Know Nepal website is filled with placeholder images. It would be nice if we had the logos of the companies to display.

## Describe the solution you'd like
A field called `logo_url` should be added to the existing data. If a company doesn't have a specific logo that can be left null. 
The logo should be ideally `96x96` in size.

## Additional context

![image](https://github.com/Know-Nepal/tech-companies/assets/60746512/cbe00952-1718-452d-aebd-b75593a274ca)

**Comment by thenishantsapkota** [comment]
Please provide your thoughts on this @susanhsrestha  @TheLearneer

**Comment by TheLearneer** [comment]
## Few notes

### Variable to use

My initial thoughts are when someone makes a contribution, they won't be able to get the URL directly, so should be fallback for just logo name for the time being?

```json
{
  "logoName": "knowNepal.png"
}
```

Later on we can maybe write an automated script that will automatically add the proper URL?
_Need feedback on this!_

#### Raw URLs

Technically we can already know what the URL will be, for e.g.
 https://raw.githubusercontent.com/Know-Nepal/.github/main/profile/assets/logo.png

so in case on this repository it would be:
https://raw.githubusercontent.com/Know-Nepal/tech-companies/main/logos/companyName.png

### Variable casing

Just to stay consistent with the other variable names, we should use **camelCase** instead of snake_case.
Thus the field should be named as `logoUrl` instead of `logo_url`.

### How to add the logos

The logos should be placed into a directory `/logos` in the root of the repository.
The file name should strictly be **camelCase** as well

### Image dimensions

I believe we will have `.png` extensions mostly, for that either 96x96 or 128x128 sounds fine to me. Let's stick to one dimension though.
We can additionally accept verctor images as well (`.svg`).

**Comment by susanhsrestha** [comment]
I think we can move forward with the plan to stick with one image dimension and use fallback for the company's logo.

**Comment by thenishantsapkota** [comment]
Sounds like a plan. Let's use the `logoName` key for the data and use the image if we have one. If the image isn't present let us use the fallback. 
To store images for logos, I suggest we use this structure.
```
├── data/
│   └── websites.json
└── images/
    ├── knowNepal.png
    ├── leapfrog.png
    └── company.png
```

**Comment by TheLearneer** [comment]
Sounds good to me. Here is a basic example so that everyone is on the same understanding level
```json
{
  "name": "Know Nepal",
  "logoName": "knowNepal.png"
}
```

```
├── data/
│   └── companies.json
└── logos/
    ├── knowNepal.png
    └── company.png
```

**Comment by thenishantsapkota** [comment]
So I'll get to work collecting the logos of the existing companies in our repository.
And I'll put placeholder values to all the companies and if logos are found I'll drop them in the logos folder.

**Comment by susanhsrestha** [comment]
_logos_ or _images_ for the directory?
